//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHangHoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETNHAP
    {
        public int CHITIETNHAPID { get; set; }
        public Nullable<int> MATHANGID { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<int> GIANHAP { get; set; }
        public Nullable<int> NHAPID { get; set; }
    
        public virtual MATHANG MATHANG { get; set; }
        public virtual NHAP NHAP { get; set; }
    }
}
