//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHangHoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHAP
    {
        public NHAP()
        {
            this.CHITIETNHAPs = new HashSet<CHITIETNHAP>();
        }
    
        public int NHAPID { get; set; }
        public Nullable<int> NHANVIENID { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
        public string DIADIEMNHAP { get; set; }
    
        public virtual ICollection<CHITIETNHAP> CHITIETNHAPs { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
