//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHangHoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class XUAT
    {
        public XUAT()
        {
            this.CHITIETXUATs = new HashSet<CHITIETXUAT>();
        }
    
        public int XUATID { get; set; }
        public Nullable<int> NHANVIENID { get; set; }
        public Nullable<int> KHACHHANGID { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
    
        public virtual ICollection<CHITIETXUAT> CHITIETXUATs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
